spring.application.name=fightsystem

spring.datasource.url=jdbc:postgresql://localhost:5432/academy
spring.datasource.username=postgres
spring.datasource.password=Lui$1227

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration